In [1]:
import pandas as pd
import numpy as np

# Car dataset
data = {
    "Name": ["Mahindra Thar", "Maruti Swift", "Mahindra Scorpio", "Tata Punch", "Hyundai Creta"],
    "Min Price (Lakh)": [11.35, 6.49, 13.62, 6.13, 11],
    "Max Price (Lakh)": [17.6, 9.6, 17.42, 10.2, 20.15],
    "Range (kmpl)": [15.2, 24.8, 22, 20.09, 17.4],
    "CC": [1497, 1197, 2184, 1199, 1497],
    "Seats": [4, 5, 7, 5, 5],
    "Variants": [19, 11, 4, 25, 28],
    "Type": ["Petrol", "Petrol", "Diesel", "Petrol", "Petrol"],
}

df = pd.DataFrame(data)
df

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type
0,Mahindra Thar,11.35,17.60,15.20,1497,4,19,Petrol
1,Maruti Swift,6.49,9.60,24.80,1197,5,11,Petrol
2,Mahindra Scorpio,13.62,17.42,22.00,2184,7,4,Diesel
3,Tata Punch,6.13,10.20,20.09,1199,5,25,Petrol
4,Hyundai Creta,11.00,20.15,17.40,1497,5,28,Petrol

In [2]:
print("Type:", type(df))
print("Columns:", list(df.columns))
print("Index:", df.index.tolist())

df

Type: <class 'pandas.DataFrame'>
Columns: ['Name', 'Min Price (Lakh)', 'Max Price (Lakh)', 'Range (kmpl)', 'CC', 'Seats', 'Variants', 'Type']
Index: [0, 1, 2, 3, 4]

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type
0,Mahindra Thar,11.35,17.60,15.20,1497,4,19,Petrol
1,Maruti Swift,6.49,9.60,24.80,1197,5,11,Petrol
2,Mahindra Scorpio,13.62,17.42,22.00,2184,7,4,Diesel
3,Tata Punch,6.13,10.20,20.09,1199,5,25,Petrol
4,Hyundai Creta,11.00,20.15,17.40,1497,5,28,Petrol

In [3]:
# Save to CSV, then load it back
df.to_csv("Car data.csv", index=False)
df_from_csv = pd.read_csv("Car data.csv")

# Save to Excel, then load it back
df.to_excel("Car data.xlsx", index=False)
df_from_excel = pd.read_excel("Car data.xlsx")

df_from_csv.tail()

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type
0,Mahindra Thar,11.35,17.60,15.20,1497,4,19,Petrol
1,Maruti Swift,6.49,9.60,24.80,1197,5,11,Petrol
2,Mahindra Scorpio,13.62,17.42,22.00,2184,7,4,Diesel
3,Tata Punch,6.13,10.20,20.09,1199,5,25,Petrol
4,Hyundai Creta,11.00,20.15,17.40,1497,5,28,Petrol

In [4]:
print("First 3 rows:")
display(df.head(3))

print("\nLast 3 rows:")
display(df.tail(3))

print("\nInfo:")
df.info()

print("\nDescribe:")
display(df.describe())

print("\nShape (rows, columns):", df.shape)

First 3 rows:

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type
0,Mahindra Thar,11.35,17.60,15.2,1497,4,19,Petrol
1,Maruti Swift,6.49,9.60,24.8,1197,5,11,Petrol
2,Mahindra Scorpio,13.62,17.42,22.0,2184,7,4,Diesel

Last 3 rows:

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type
2,Mahindra Scorpio,13.62,17.42,22.00,2184,7,4,Diesel
3,Tata Punch,6.13,10.20,20.09,1199,5,25,Petrol
4,Hyundai Creta,11.00,20.15,17.40,1497,5,28,Petrol

Info:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              5 non-null      str
 1   Min Price (Lakh)  5 non-null      float64
 2   Max Price (Lakh)  5 non-null      float64
 3   Range (kmpl)      5 non-null      float64
 4   CC                5 non-null      int64
 5   Seats             5 non-null      int64
 6   Variants          5 non-null      int64
 7   Type              5 non-null      str
dtypes: float64(3), int64(3), str(2)
memory usage: 452.0 bytes

Describe:

,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants
count,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,9.71800,14.994000,19.898000,1514.800000,5.200000,17.400000
std,3.27209,4.778565,3.768159,402.861266,1.095445,9.914636
min,6.13000,9.600000,15.200000,1197.000000,4.000000,4.000000
25%,6.49000,10.200000,17.400000,1199.000000,5.000000,11.000000
50%,11.00000,17.420000,20.090000,1497.000000,5.000000,19.000000
75%,11.35000,17.600000,22.000000,1497.000000,5.000000,25.000000
max,13.62000,20.150000,24.800000,2184.000000,7.000000,28.000000

Shape (rows, columns): (5, 8)

In [5]:
# loc: label-based selection
print("loc example (rows 0-2, specific columns):")
display(df.loc[0:2, ["Name", "Type", "CC"]])

# iloc: position-based selection
print("\niloc example (first 3 rows, first 3 columns):")
display(df.iloc[0:3, 0:3])

# Boolean indexing: filter rows where Type is 'Petrol'
print("\nBoolean indexing (Type == 'Petrol'):")
display(df[df["Type"] == "Petrol"])

loc example (rows 0-2, specific columns):

               Name    Type    CC
0     Mahindra Thar  Petrol  1497
1      Maruti Swift  Petrol  1197
2  Mahindra Scorpio  Diesel  2184

iloc example (first 3 rows, first 3 columns):

               Name  Min Price (Lakh)  Max Price (Lakh)
0     Mahindra Thar             11.35             17.60
1      Maruti Swift              6.49              9.60
2  Mahindra Scorpio             13.62             17.42

Boolean indexing (Type == 'Petrol'):

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type
0,Mahindra Thar,11.35,17.60,15.20,1497,4,19,Petrol
1,Maruti Swift,6.49,9.60,24.80,1197,5,11,Petrol
3,Tata Punch,6.13,10.20,20.09,1199,5,25,Petrol
4,Hyundai Creta,11.00,20.15,17.40,1497,5,28,Petrol